### ISSUE TITLE
Refactor entry page to reduce number of current WildFly releases.

### ISSUE THREAD

**Issue by darranl** [wildfly/wildfly.org#267]
The older releases could be moved to an archive but at the moment the growing list is pushing the additional content further down the page.

**Comment by yersan** [comment]
@darranl I guess you are talking about WildFly documentation landing page, in that case, changes/issue should be at https://github.com/wildfly/wildfly.github.io

**Comment by bstansberry** [comment]
@darranl I'm closing this, as Yeray is right -- the relevant code is controlled from https://github.com/wildfly/wildfly.github.io
