### ISSUE TITLE
Add a description on the download section about which Microprofile spec is supported by the server 

### ISSUE THREAD

**Issue by yersan** [wildfly/wildfly.org#283]
I got the impression it could be difficult for the users to understand that WildFly supports Microprofile spec and which version is supported on each WildFly release. We have the release notes and news, but maybe we should do it more clear.

I've opened the issue to suggest including the Microprofile Spec in the description text that appears on the download link, e.g:

instead of "Jakarta EE XX Full & Web Distribution", add "Jakarta EE XX Full & Web Distribution and Microprofile XX"

**Comment by darranl** [comment]
I am not sure if this came up before but is WildFly committed to MicroProfile version in the way it presently identifies a Jakarta EE version?

**Comment by yersan** [comment]
That's a good point, I'm unable to give you a response, I hope, someone can.

My only point here is I recently tried to run quick Microprofile application examples on WildFly and I found it somehow difficult to understand at first glance which MP version I should use with my WildFly release. It could have been a personal issue, but maybe other users could find it difficult too. Even more for new users unfamiliar with WildFly that arrive looking whether the server can be used to run MP applications.

**Comment by yersan** [comment]
Any other feedback about this? In any case, pinging @bstansberry / @jamezp / @kabir  do you want to share your opinion?

Otherwise, I'll close this request.

**Comment by yersan** [comment]
Any other feedback about this? In any case, pinging @bstansberry / @jamezp / @kabir  do you want to share your opinion?

Otherwise, I'll close this request.

**Comment by bstansberry** [comment]
@yersan I don't think we should do this. For a couple releases now WF has not chosen to implement the full MP Platform because we do not want to implement MP Metrics. We may implement MP 7 if the possible change re MP Metrics occurs, but then some other issue with the platform may arise.

I'm going to close this just to clean up the issue list, but please feel free to re-open. I don't intend to reject further discussion.
