### ISSUE TITLE
Blog Post: How to contribute to WildFly

### ISSUE THREAD

**Issue by fjuma** [wildfly/wildfly.org#500]
Create a blog post that describes how to contribute to the WildFly project for new contributors.

**Comment by RanabirChakraborty** [comment]
Hello @fjuma Can you please summarise how you see the Article would be?

IMO, I have thought to add the below points:

- Get Acquainted with WildFly (This will include the WildFly repo link, related documentations)
- Set Up Your Development Environment
- Create an issue or Follow the JIRA, select an issue and send a PR
- Participate in code review.
- Engage with the Community

**Comment by bstansberry** [comment]
Resolved via #546
