### ISSUE TITLE
Blog Post: How to connect with the WildFly community

### ISSUE THREAD

**Issue by fjuma** [wildfly/wildfly.org#502]
Create a blog post that explains the different ways to connect with the WildFly community (e.g., WildFly google group, Zulip, wildfly-dev mailing list).

**Comment by RanabirChakraborty** [comment]
@fjuma I can work on it, once we close our social media preference survey.

**Comment by fjuma** [comment]
Thanks @RanabirChakraborty! I've assigned it to you.

**Comment by RanabirChakraborty** [comment]
Hello @fjuma, Can you please summarise how you see the Article?

IMO, I have thought to add the below points:

- Get an idea about WildFly (Explore the WildFly Website, Get started with WildFly, Fork the WildFly Repository on GitHub and play with it)
- Join the WildFly Google group and Engage in the WildFly Forums
- Follow WildFly on Social Media
- Attend WildFly Community Events (promotion of WildFly mini-conference)
- Provide and Receive Support

**Comment by fjuma** [comment]
That all sounds good! Would also be good to mention the wildfly-dev mailing list.

**Comment by fjuma** [comment]
Marking this one as closed since the blog post has been published:

https://www.wildfly.org/news/2024/03/01/How-to-contribute-to-WildFly/

**Comment by fjuma** [comment]
@RanabirChakraborty Sorry, I closed this one by accident. Just realized the blog post I linked was actually for this issue:

https://github.com/wildfly/wildfly.org/issues/500

**Comment by bstansberry** [comment]
Resolved via #618
