### ISSUE TITLE
Guide: Use case driven guides for credential-stores

### ISSUE THREAD

**Issue by PrarthonaPaul** [wildfly/wildfly.org#509]
Use cases: 

- replace cleartext passwords in credential-reference 
- Encrypted expressions 
- WildFly client configuration

**Comment by bstansberry** [comment]
@PrarthonaPaul  Note there is also #580 which is a specific case of a use-case driven guide involving a credential-store. We should have a coherent approach.

#580 is step 3 in a multi-step series of datasource guides, so we have time to think about this before we get to that step.

**Comment by PrarthonaPaul** [comment]
https://wildfly-security.github.io/wildfly-elytron/blog/credential-stores-on-client-side/
https://wildfly-security.github.io/wildfly-elytron/blog/credential-store-for-encrypted-expressions/
https://wildfly-security.github.io/wildfly-elytron/blog/credential-store-for-passwords/
