### ISSUE TITLE
The 'Older Posts' link in the 'news' pages should have consistent placement

### ISSUE THREAD

**Issue by bstansberry** [wildfly/wildfly.org#564]
Minor pet peeve, and one may not be fixable without major Jekyll surgery. (I have no idea, because I haven't looked.)

On https://www.wildfly.org/news/ the 'Older Posts' link is bottom left while on https://www.wildfly.org/news/page/2/ and later it is bottom right.

This is annoying. It should always be bottom right.

I'm not asking for major Jekyll surgery here. It's just an annoyance that would be good to fix if it's easy.

**Comment by hpehl** [comment]
I'll have a look.
