### ISSUE TITLE
Blog Post: WildFly Mini Conference Event Recap

### ISSUE THREAD

**Issue by fjuma** [wildfly/wildfly.org#565]
Create a blog post for wildfly.org with a recap of the [WildFly Mini Conference](https://www.wildfly.org/conference/).

The post can also remind people to provide their feedback about the conference:
https://tinyurl.com/wildfly

We can also provide a link to the YouTube video for anyone who missed the event:
https://www.youtube.com/watch?v=_8g1rZ80u2A

We can also point to the slides/resources from the sessions.

**Comment by hpehl** [comment]
I’ll start writing a blog post about the conference. My idea is to update wildfly.org/conference and link the slides and videos from there. The blog post would then contain the recap and the link to the updated wildfly.org/conference page.

**Comment by hpehl** [comment]
See https://github.com/wildfly/wildfly.org/pull/572
