### ISSUE TITLE
Add a couple links to the Getting Started Page

### ISSUE THREAD

**Issue by fjuma** [wildfly/wildfly.org#574]
It would be great to update the Getting Started Page (https://www.wildfly.org/get-started/) to add links to:

* The new [guides page](https://www.wildfly.org/guides/)
* Harald's [talk](https://youtu.be/_8g1rZ80u2A?t=743) from the mini conference about getting started with WildFly

**Comment by hpehl** [comment]
I'll start working on this.

**Comment by jmesnil** [comment]
@hpehl is this issue done by #594 or is there any additional link you wanted to add?

**Comment by hpehl** [comment]
@jmesnil, sorry for the late reply. Yes, this is done. I'm closing this.
