### ISSUE TITLE
Guide: Use of Wildfly and AMQP connector connected to AMQ 7 with two-way SSL on Openshift

### ISSUE THREAD

**Issue by mnovak1** [wildfly/wildfly.org#585]
The primary focus will be on the implementation of a two-way SSL configuration for connecting to a remote AMQ 7 messaging broker instance deployed on Openshift.

**Comment by mnovak1** [comment]
@fjuma I plan to work on this during this week. I would like to use Wildfly Glow to build Reactive Messaging bootable jar with AMQP connector. AMQ 7 operator be used to deploy AMQ 7 instance secured with 2-way ssl.

**Comment by fjuma** [comment]
That's great @mnovak1! Thanks very much!
