### ISSUE TITLE
Add a /releases page to list all Release announcements

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly.org#611]
It's quite difficult to navigate the /news to find all release announcements that contain a wealth of information.

All these posts have the `release + announcement` tags (or should have them), so we could use these tags to generate a /releases page that would list only the release announcements.
This page would give a good overview of the evolution of the project. When I'm upgrading from WildFly x to WildFly x+2, I've a good source of information to see what happened across these 2 versions.

We could then add this page at the top of the https://www.wildfly.org/news/ page for better SEO.

**Comment by jmesnil** [comment]
Technically, that's the same thing that browsing https://www.wildfly.org/downloads/ and opening all the "Release Notes" link but I'd prefer to have it in a single page to reduce cognitive load.

**Comment by jamezp** [comment]
What could be interesting too is to have a `release-feed.xml` we could link from there to only see releases.
