### ISSUE TITLE
Create an end of year message for 2024

### ISSUE THREAD

**Issue by bstansberry** [wildfly/wildfly.org#702]
A new version of https://www.wildfly.org/news/2023/12/22/Year-end-message/

Ideas via comments are welcome!

**Comment by jfdenise** [comment]
* 2 WildFly Mini Conferences
* Provisioning: WildFly Glow new project, 1.2.0.Final today. Used by WildFly testsuite, WildFly QS. integerated in WildFly Maven Plugin.
