### ISSUE TITLE
Enable HTTPS for wildfly.org

### ISSUE THREAD

**Issue by jawnsy** [wildfly/wildfly.org#79]
Hello,

Please consider making http://wildfly.org accessible via https://wildfly.org. There has been a general trend toward encrypting web sites, accelerated by the Snowden revelations, and nowadays [Google ranks web sites higher if they are SSL/TLS-enabled](https://webmasters.googleblog.com/2014/08/https-as-ranking-signal.html). This also has the benefit of [preventing ads from being injected](https://security.googleblog.com/2015/05/new-research-ad-injection-economy.html) into web sites by unscrupulous third-parties (coffee shops, hotels, airports, ...)

As certificates are now widely available for free via initiatives like [Let's Encrypt](https://letsencrypt.org/) and [CloudFlare](https://www.cloudflare.com/ssl/), it should be straightforward to:
1. Serve web content via HTTPS (stop redirecting to the plain-HTTP site)
2. Redirect from HTTP to HTTPS
3. Instruct browsers to optimistically upgrade to HTTPS using `Upgrade-Insecure-Requests` header
4. Require SSL using `Strict-Transport-Security` headers

(These can be done one at a time to ease the transition)

Cheers,

Jonathan

**Comment by jawnsy** [comment]
Jason, Tomaz, Brian,

Sorry for the blanket ping, but you were the last three committers to this project, so I wanted to make sure someone saw this.  It should be a relatively quick/easy/painless change and help improve our search engine-fu (maybe famous last words?)

@n1hility @ctomc @bstansberry

**Comment by ctomc** [comment]
@jawnsy we all agree with you on having SSL enabled, but web server where we publish static website of wildfly.org is not under our control and as such we cannot enable SSL, we asked administrators for it but it is still in the queue.
Maybe we might just move it to where we have our CI, which we control completely.

**Comment by bstansberry** [comment]
The site now uses HTTPS (and HSTS).
