### ISSUE TITLE
Add checksum files for Wildfly downloads

### ISSUE THREAD

**Issue by nerro** [wildfly/wildfly.org#87]
Hi,

I build custom Docker image (not official https://store.docker.com/community/images/jboss/wildfly) with specific java version for my projects and I would check integrity of the downloaded archive with `sha1sum`.

I think it's actually a common use case (downloading Wildfly archive and compare checksum). Is it possible to add a file with checksums (`md5`, `sha1`, `sha256`) in directories with Wildfly distributions and links on the wildfly.org/downloads too?

Thanks.

**Comment by bangnab** [comment]
In the official jboss/wildfly docker image (https://github.com/jboss-dockerfiles/wildfly/blob/master/Dockerfile) they have the sha1. You can copy that or calculate your own. But I also think there should be a more standard place to get the sha1 sums for each version.

**Comment by nerro** [comment]
@bangnab, I saw this solution, but it would be more correct in my opinion if I did not calculate checksums myself.

Actually the best solution would be to provide signed checksums (e.g. like for nodejs downloads https://nodejs.org/dist/v6.11.3/SHASUMS256.txt.asc or simple hashes like for golang  https://golang.org/dl/).

**Comment by mhlulani** [comment]
Is there any chance this was added, I think it's a must have.
It was there before but was removed

**Comment by kfogel** [comment]
+1, FWIW.  I went looking for checksums and/or GPG signatures at http://wildfly.org/downloads/ -- and would have used them to confirm that my download wasn't tampered with, or at least to raise the probability that my download hadn't been tampered with :-)  -- but there were none provided.

**Comment by bangnab** [comment]
@kfogel Note that one can also use https for that link:
https://repo1.maven.org/maven2/org/wildfly/wildfly-dist/11.0.0.Final/

**Comment by kfogel** [comment]
Thanks, @bangnab.  I updated my comment to reflect that, since it's slightly security-sensitive in this context.

**Comment by bstansberry** [comment]
The last few releases now have sha1 links on https://wildfly.org/downloads

**Comment by janst44** [comment]
Not sure where else to put this comment, but looks like they've messed up which hash goes where in the latest 26.1.1 release

**Comment by janst44** [comment]
@bstansberry  I'm sorry. I should have deleted this comment, i created an issue then deleted it, but forgot about this comment here. I was comparing the wrong sha1 file for my download.

**Comment by bstansberry** [comment]
Thanks, @janst44!
